version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

# TODO добавить сервисы
  gateway:
    image: gateway
    build: ./gateway/
    ports:
      - "8080:8080"
      
  reservation:
    image: reservation
    build: ./reservation/
    ports:
      - "8070:8070"
    depends_on:
      - postgres
      
  library:
    image: library
    build: ./library/
    ports:
      - "8060:8060"
    depends_on:
      - postgres
      
  rating:
    image: rating
    build: ./rating/
    ports:
      - "8050:8050"
    depends_on:
      - postgres

volumes:
  db-data: